 # ETL Project
 
 ### By Patricia Castro
----------------------------

Crime data in Los Angeles from data.gov

In [ ]:
## Shift + tab for methods info
## command + / = comments out all

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import colors

import numpy as np
import os

In [2]:
#read csv file
df = pd.read_csv("Resources/CrimeData_2010-Present.csv",parse_dates=True)

In [3]:
df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,11401303,9/13/10,9/12/10,45,14,Pacific,1485,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,"(33.9599, -118.3962)"
1,70309629,8/9/10,8/9/10,1515,13,Newton,1324,946,OTHER MISCELLANEOUS CRIME,344,...,NaN,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,"(34.0224, -118.2524)"
2,100100508,1/8/10,1/7/10,2005,1,Central,182,330,BURGLARY FROM VEHICLE,344,...,NaN,IC,Invest Cont,330.0,NaN,NaN,NaN,PICO BL,GRAND AV,"(34.0389, -118.2643)"
3,100100511,1/9/10,1/6/10,2100,1,Central,132,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,NaN,IC,Invest Cont,341.0,998.0,NaN,NaN,200 S OLIVE ST,NaN,"(34.0538, -118.2488)"
4,100100523,1/15/10,1/15/10,245,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,AA,Adult Arrest,740.0,NaN,NaN,NaN,1100 S OLIVE ST,NaN,"(34.0409, -118.2609)"

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.shape

(1048575, 26)

## Check variables

In [6]:
#print the dataframe columns

cols= list(df.columns)
print(cols)

['DR Number', 'Date Reported', 'Date Occurred', 'Time Occurred', 'Area ID', 'Area Name', 'Reporting District', 'Crime Code', 'Crime Code Description', 'MO Codes', 'Victim Age', 'Victim Sex', 'Victim Descent', 'Premise Code', 'Premise Description', 'Weapon Used Code', 'Weapon Description', 'Status Code', 'Status Description', 'Crime Code 1', 'Crime Code 2', 'Crime Code 3', 'Crime Code 4', 'Address', 'Cross Street', 'Location ']

In [7]:
#remove spaces from the variable name by assigning the values to a new variable
df['Location'] = df['Location ']

In [8]:
#removed old column
df.drop(columns=['Location '], axis=1, inplace = True)

In [9]:
#check column changes
df.columns

Index(['DR Number', 'Date Reported', 'Date Occurred', 'Time Occurred',
       'Area ID', 'Area Name', 'Reporting District', 'Crime Code',
       'Crime Code Description', 'MO Codes', 'Victim Age', 'Victim Sex',
       'Victim Descent', 'Premise Code', 'Premise Description',
       'Weapon Used Code', 'Weapon Description', 'Status Code',
       'Status Description', 'Crime Code 1', 'Crime Code 2', 'Crime Code 3',
       'Crime Code 4', 'Address', 'Cross Street', 'Location'],
      dtype='object')

In [10]:
# reduce the dataframe from 1.9 million to 1,000 rows
newdf = df.loc[0:1000,:]
newdf

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,11401303,9/13/10,9/12/10,45,14,Pacific,1485,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,"(33.9599, -118.3962)"
1,70309629,8/9/10,8/9/10,1515,13,Newton,1324,946,OTHER MISCELLANEOUS CRIME,344,...,NaN,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,"(34.0224, -118.2524)"
2,100100508,1/8/10,1/7/10,2005,1,Central,182,330,BURGLARY FROM VEHICLE,344,...,NaN,IC,Invest Cont,330.0,NaN,NaN,NaN,PICO BL,GRAND AV,"(34.0389, -118.2643)"
3,100100511,1/9/10,1/6/10,2100,1,Central,132,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,NaN,IC,Invest Cont,341.0,998.0,NaN,NaN,200 S OLIVE ST,NaN,"(34.0538, -118.2488)"
4,100100523,1/15/10,1/15/10,245,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,AA,Adult Arrest,740.0,NaN,NaN,NaN,1100 S OLIVE ST,NaN,"(34.0409, -118.2609)"
5,100100552,1/23/10,1/23/10,1225,1,Central,192,237,CHILD NEGLECT (SEE 300 W.I.C.),1251,...,NaN,IC,Invest Cont,237.0,NaN,NaN,NaN,1300 S FLOWER ST,NaN,"(34.0401, -118.2668)"
6,100100562,1/28/10,1/28/10,2345,1,Central,152,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 2000,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,626.0,NaN,NaN,NaN,500 S GRAND AV,NaN,"(34.0502, -118.254)"
7,100100575,2/1/10,1/31/10,1720,1,Central,181,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1402,...,NaN,AA,Adult Arrest,341.0,NaN,NaN,NaN,1100 S FIGUEROA ST,NaN,"(34.0437, -118.2652)"
8,100100610,2/11/10,2/10/10,1800,1,Central,162,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0325 1402,...,NaN,AA,Adult Arrest,442.0,998.0,NaN,NaN,700 W 7TH ST,NaN,"(34.048, -118.2577)"
9,100100616,2/11/10,2/11/10,1515,1,Central,192,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1212,...,NaN,AA,Adult Arrest,341.0,NaN,NaN,NaN,PICO,GRAND,"(34.0389, -118.2643)"
10,100100638,2/20/10,2/20/10,100,1,Central,164,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,AA,Adult Arrest,740.0,NaN,NaN,NaN,100 W 7TH ST,NaN,"(34.0439, -118.2514)"
11,100100650,2/25/10,2/25/10,30,1,Central,111,310,BURGLARY,0344 1251,...,NaN,IC,Invest Cont,310.0,NaN,NaN,NaN,500 N FIGUEROA ST,NaN,"(34.0617, -118.2469)"
12,100100654,2/27/10,2/27/10,1955,1,Central,174,946,OTHER MISCELLANEOUS CRIME,NaN,...,NaN,AA,Adult Arrest,946.0,NaN,NaN,NaN,W 7TH ST,S SPRING ST,"(34.0445, -118.2523)"
13,100100660,3/1/10,3/1/10,100,1,Central,148,648,ARSON,1501,...,NaN,IC,Invest Cont,648.0,NaN,NaN,NaN,5TH,SAN PEDRO ST,"(34.0435, -118.2427)"
14,100100697,3/12/10,3/12/10,1520,1,Central,151,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,NaN,AA,Adult Arrest,341.0,998.0,NaN,NaN,7TH,FIGUEROA,"(34.0499, -118.2614)"
15,100100725,3/18/10,3/18/10,15,1,Central,145,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",400,...,MACE/PEPPER SPRAY,AA,Adult Arrest,230.0,NaN,NaN,NaN,400 S MAIN ST,NaN,"(34.0482, -118.2472)"
16,100100726,3/19/10,3/19/10,1000,13,Newton,1307,624,BATTERY - SIMPLE ASSAULT,0416 0429 0917 1804,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,800 E 8TH ST,NaN,"(34.0371, -118.2475)"
17,100100733,3/21/10,3/21/10,1000,11,Northeast,1171,946,OTHER MISCELLANEOUS CRIME,1402,...,NaN,IC,Invest Cont,946.0,998.0,NaN,NaN,WAVERLY,SUNSET BL,"(34.0917, -118.2741)"
18,100100738,3/22/10,3/19/10,1730,1,Central,195,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,0416 0552,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,627.0,NaN,NaN,NaN,1800 S MAIN ST,NaN,"(34.0317, -118.2641)"
19,100100740,3/25/10,3/22/10,1915,1,Central,142,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",416,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,230.0,NaN,NaN,NaN,4TH ST,GRAND AV,"(34.0516, -118.2526)"
20,100100744,3/23/10,3/23/10,230,1,Central,101,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0311 0329 0906,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,1200 INNES AV,NaN,"(34.0717, -118.2493)"
21,100100753,3/25/10,3/25/10,240,1,Central,171,946,OTHER MISCELLANEOUS CRIME,0906 1501,...,NaN,AA,Adult Arrest,946.0,NaN,NaN,NaN,900 GEORGIA ST,NaN,"(34.0475, -118.2657)"
22,100100764,4/1/10,3/29/10,2320,1,Central,176,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,SAN PEDRO ST,9TH ST,"(34.0373, -118.2503)"
23,100100792,4/10/10,4/10/10,1710,1,Central,135,210,ROBBERY,302,...,HAND GUN,IC,Invest Cont,210.0,NaN,NaN,NaN,100 E 3RD ST,NaN,"(34.0496, -118.2458)"
24,100100799,4/12/10,4/12/10,1700,1,Central,111,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1251 1300,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,YALE,COLLEGE,"(34.0672, -118.2385)"
25,100100802,4/14/10,4/14/10,1515,1,Central,155,946,OTHER MISCELLANEOUS CRIME,914,...,NaN,AA,Adult Arrest,946.0,NaN,NaN,NaN,200 E 6TH ST,NaN,"(34.0446, -118.249)"
26,100100803,4/14/10,4/14/10,915,1,Central,161,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,NaN,IC,Invest Cont,341.0,998.0,NaN,NaN,700 S FIGUEROA ST,NaN,"(34.0494, -118.2599)"
27,100100812,4/16/10,4/16/10,800,1,Central,152,441,THEFT PLAIN - ATTEMPT,1402,...,NaN,IC,Invest Cont,441.0,998.0,NaN,NaN,7TH,OLIVE,"(34.0467, -118.2556)"
28,100100826,4/17/10,4/17/10,1300,1,Central,124,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 1402,...,NaN,IC,Invest Cont,745.0,998.0,NaN,NaN,1ST,MAIN ST,"(34.0522, -118.2434)"
29,100100828,4/17/10,4/17/10,1900,1,Central,111,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,0400 0421 0432 1402,...,VERBAL THREAT,IC,Invest Cont,930.0,998.0,NaN,NaN,CESAR E CHAVEZ BL,SPRING ST,"(34.0582, -118.2387)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,100112676,6/19/10,6/14/10,730,1,Central,166,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),NaN,...,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,600 WALL ST,NaN,"(34.0435, -118.2471)"
972,100112677,6/19/10,6/19/10,1000,1,Central,157,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6TH,CROCKER,"(34.0412, -118.2436)"
973,100112685,6/19/10,6/19/10,1500,1,Central,166,624,BATTERY - SIMPLE ASSAULT,416,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,624.0,NaN,NaN,NaN,7TH,SAN JULIAN,"(34.0407, -118.2468)"
974,100112700,6/19/10,6/19/10,1330,1,Central,192,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",344,...,NaN,AA,Adult Arrest,341.0,NaN,NaN,NaN,1300 S HOPE ST,NaN,"(34.0395, -118.2656)"
975,100112706,6/20/10,6/17/10,2155,1,Central,192,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,400 W VENICE BL,NaN,"(34.0365, -118.2676)"
976,100112709,6/20/10,6/20/10,200,1,Central,163,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1251,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,700 S BROADWAY,NaN,"(34.0452, -118.2534)"
977,100112715,6/20/10,6/20/10,830,1,Central,142,440,THEFT PLAIN - PETTY ($950 & UNDER),325,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,440.0,NaN,NaN,NaN,400 S FIGUEROA ST,NaN,"(34.0535, -118.256)"
978,100112724,6/20/10,6/17/10,2100,1,Central,192,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1307,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,FIGUEROA,18TH ST,"(34.0359, -118.2711)"
979,100112727,6/20/10,6/20/10,1030,1,Central,142,928,THREATENING PHONE CALLS/LETTERS,NaN,...,NaN,IC,Invest Cont,928.0,NaN,NaN,NaN,400 S FIGUEROA ST,NaN,"(34.0535, -118.256)"
980,100112730,6/20/10,6/20/10,1700,1,Central,156,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,400,...,VERBAL THREAT,IC,Invest Cont,930.0,NaN,NaN,NaN,500 S SAN PEDRO ST,NaN,"(34.0442, -118.2439)"
981,100112731,6/20/10,6/20/10,1700,1,Central,156,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,400,...,VERBAL THREAT,IC,Invest Cont,930.0,NaN,NaN,NaN,500 S SAN PEDRO ST,NaN,"(34.0442, -118.2439)"
982,100112735,6/21/10,6/21/10,1000,1,Central,111,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,600 N GRAND AV,NaN,"(34.0606, -118.2439)"
983,100112738,6/21/10,4/20/10,1,1,Central,145,946,OTHER MISCELLANEOUS CRIME,914,...,NaN,IC,Invest Cont,946.0,NaN,NaN,NaN,100 E 5TH ST,NaN,"(34.0467, -118.2485)"
984,100112739,6/21/10,6/17/10,2130,1,Central,162,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1300,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,8TH,FLOWER,"(34.0473, -118.2601)"
985,100112748,6/21/10,6/21/10,1220,1,Central,192,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0601 1402,...,NaN,AA,Adult Arrest,740.0,998.0,NaN,NaN,1300 S FLOWER ST,NaN,"(34.0401, -118.2668)"
986,100112764,6/21/10,6/13/10,1600,1,Central,152,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",344,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,500 S FLOWER ST,NaN,"(34.0516, -118.2561)"
987,100112765,6/21/10,6/21/10,1410,1,Central,171,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0601,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,900 W OLYMPIC BL,NaN,"(34.0454, -118.2657)"
988,100112768,6/21/10,6/21/10,700,1,Central,111,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,600 N BUNKER HILL AV,NaN,"(34.0613, -118.2446)"
989,100112786,6/17/10,6/17/10,2130,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1300,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,OLIVE ST,15TH ST,"(34.0359, -118.2648)"
990,100112792,6/22/10,6/17/10,2010,1,Central,192,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),329,...,NaN,IC,Invest Cont,745.0,NaN,NaN,NaN,17TH ST,FIGUEROA ST,"(34.0373, -118.2707)"
991,100112799,6/22/10,6/17/10,930,1,Central,185,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,900 S BROADWAY,NaN,"(34.0423, -118.2561)"
992,100112800,6/21/10,6/21/10,830,1,Central,127,755,BOMB SCARE,0404 2109 2210,...,VERBAL THREAT,IC,Invest Cont,755.0,995.0,NaN,NaN,100 N LOS ANGELES ST,NaN,"(34.0515, -118.2424)"
993,100112811,6/22/10,6/20/10,100,1,Central,171,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1251,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,900 S FIGUEROA ST,NaN,"(34.0462, -118.2628)"
994,100112818,6/22/10,5/5/10,1330,1,Central,119,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",344,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,800 N ALAMEDA ST,NaN,"(34.0563, -118.2374)"
995,100112821,6/22/10,6/17/10,1630,1,Central,192,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0601,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,1300 S FLOWER ST,NaN,"(34.0401, -118.2668)"
996,100112825,6/22/10,6/21/10,1600,1,Central,185,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0104 0344 0601,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,100 E 12TH ST,NaN,"(34.0376, -118.2594)"
997,100112827,6/22/10,6/22/10,745,1,Central,152,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",344,...,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,500 S FLOWER ST,NaN,"(34.0516, -118.2561)"
998,100112829,6/22/10,6/21/10,630,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1300,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,600 W PICO BL,NaN,"(34.0401, -118.2668)"
999,100112830,6/22/10,6/17/10,2230,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0601,...,NaN,IC,Invest Cont,740.0,NaN,NaN,NaN,1000 S OLIVE ST,NaN,"(34.0423, -118.2595)"
1000,100112833,6/22/10,6/19/10,1400,1,Central,156,928,THREATENING PHONE CALLS/LETTERS,432,...,NaN,IC,Invest Cont,928.0,NaN,NaN,NaN,500 S SAN PEDRO ST,NaN,"(34.0442, -118.2439)"

In [11]:
#check content of the Location variable
     #has latitud and longitude together
newdf['Location'].head()

0    (33.9599, -118.3962)
1    (34.0224, -118.2524)
2    (34.0389, -118.2643)
3    (34.0538, -118.2488)
4    (34.0409, -118.2609)
Name: Location, dtype: object

In [12]:
# Separate the content of the Location variable. Latitude and longitude should be separate variables.

# Create two lists for the loop results to be placed
lat = []
lon = []

# For each row in a varible,
for row in newdf['Location']:
    # Try to,
    try:
        # Split the row by comma and append
        # everything before the comma to lat
        lat.append(row.split(',')[0])
        # Split the row by comma and append
        # everything after the comma to lon
        lon.append(row.split(',')[1])
    # But if you get an error
    except:
        # append a missing value to lat
        lat.append(np.NaN)
        # append a missing value to lon
        lon.append(np.NaN)

# Create two new columns from lat and lon
newdf['latitude']= lat
newdf['longitude'] = lon

/Users/pcr_23/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/pcr_23/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [13]:
newdf.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,latitude,longitude
0,11401303,9/13/10,9/12/10,45,14,Pacific,1485,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,"(33.9599, -118.3962)",(33.9599,-118.3962)
1,70309629,8/9/10,8/9/10,1515,13,Newton,1324,946,OTHER MISCELLANEOUS CRIME,344,...,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,"(34.0224, -118.2524)",(34.0224,-118.2524)
2,100100508,1/8/10,1/7/10,2005,1,Central,182,330,BURGLARY FROM VEHICLE,344,...,Invest Cont,330.0,NaN,NaN,NaN,PICO BL,GRAND AV,"(34.0389, -118.2643)",(34.0389,-118.2643)
3,100100511,1/9/10,1/6/10,2100,1,Central,132,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,Invest Cont,341.0,998.0,NaN,NaN,200 S OLIVE ST,NaN,"(34.0538, -118.2488)",(34.0538,-118.2488)
4,100100523,1/15/10,1/15/10,245,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,Adult Arrest,740.0,NaN,NaN,NaN,1100 S OLIVE ST,NaN,"(34.0409, -118.2609)",(34.0409,-118.2609)

In [14]:
#check results

newdf['latitude'].head()

#parenthesis should be removed from the variable

0    (33.9599
1    (34.0224
2    (34.0389
3    (34.0538
4    (34.0409
Name: latitude, dtype: object

In [15]:
#check results

newdf['longitude'].head()

#parenthesis should be removed from the variable

0     -118.3962)
1     -118.2524)
2     -118.2643)
3     -118.2488)
4     -118.2609)
Name: longitude, dtype: object

In [16]:
#remove parenthesis of the latitude variable with the replace method

newdf['latitude'].replace(regex=True,inplace=True,to_replace=r'\(',value=r'')
newdf['latitude'].head()

/Users/pcr_23/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5890: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

0    33.9599
1    34.0224
2    34.0389
3    34.0538
4    34.0409
Name: latitude, dtype: object

In [17]:
#remove parenthesis of the longitude variable with the replace method

newdf['longitude'].replace(regex=True,inplace=True,to_replace=r'\)',value=r'')
newdf['longitude'].head()

0     -118.3962
1     -118.2524
2     -118.2643
3     -118.2488
4     -118.2609
Name: longitude, dtype: object

In [18]:
#check results
newdf[['latitude', 'longitude']].head()

  latitude   longitude
0  33.9599   -118.3962
1  34.0224   -118.2524
2  34.0389   -118.2643
3  34.0538   -118.2488
4  34.0409   -118.2609

In [19]:
#check data type 
newdf['latitude'].dtype

dtype('O')

In [20]:
#change data type of the latitude and longitude column from object type to float

newdf['latitude']=newdf['latitude'].astype(str).astype(float)

/Users/pcr_23/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
newdf['longitude']= newdf['longitude'].astype(str).astype(float)

/Users/pcr_23/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [22]:
#check change
newdf['latitude'].dtype

dtype('float64')

In [23]:
#check change
newdf['longitude'].dtype

dtype('float64')

In [24]:
# check data type for all columns in the dataframe
newdf.dtypes

DR Number                   int64
Date Reported              object
Date Occurred              object
Time Occurred               int64
Area ID                     int64
Area Name                  object
Reporting District          int64
Crime Code                  int64
Crime Code Description     object
MO Codes                   object
Victim Age                  int64
Victim Sex                 object
Victim Descent             object
Premise Code              float64
Premise Description        object
Weapon Used Code          float64
Weapon Description         object
Status Code                object
Status Description         object
Crime Code 1              float64
Crime Code 2              float64
Crime Code 3              float64
Crime Code 4              float64
Address                    object
Cross Street               object
Location                   object
latitude                  float64
longitude                 float64
dtype: object

In [25]:
#test the function to get zip code from latitude and longitude

from math import sin, cos, sqrt, atan2, radians
import math
import json
fname = 'us-zip-code-latitude-and-longitude.json'
loadedLatLongData = json.load(open(fname))


def distanceV(lat1, lon1,lat2, lon2):
    #lat1, lon1 = origin
    #lat2, lon2 = destination
    radius = 6371 # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d

def computeNearestZip(latitude, longitude):
    smallestDistance = 1000000
    smallestZip = None
    for data in loadedLatLongData:
        if ("fields" in data):
            distancedata = data["fields"]
            if("latitude" in distancedata and "longitude" in distancedata and "zip" in distancedata):
                zipcode = distancedata["zip"]
                lat1 = distancedata["latitude"]
                long1 = distancedata["longitude"]
                distance = distanceV(latitude,longitude, lat1,long1)

                if(distance <smallestDistance):
                    smallestZip = zipcode
                    smallestDistance = distance


    return smallestZip

In [26]:
computeNearestZip(33.9599, -118.3962)

'90045'

In [27]:
df['Location'].head()

0    (33.9599, -118.3962)
1    (34.0224, -118.2524)
2    (34.0389, -118.2643)
3    (34.0538, -118.2488)
4    (34.0409, -118.2609)
Name: Location, dtype: object

In [28]:
# remove left parenthesis from the Location variable
df['Location'].replace(regex=True,inplace=True,to_replace=r'\)',value=r'')

In [29]:
# remove right parenthesis from the Location variable
df['Location'].replace(regex=True,inplace=True,to_replace=r'\(',value=r'')

In [30]:
df['Location'].replace(regex=True,inplace=True,to_replace=r'\,',value=r'')

In [31]:
#check results
df['Location'].head()

0    33.9599 -118.3962
1    34.0224 -118.2524
2    34.0389 -118.2643
3    34.0538 -118.2488
4    34.0409 -118.2609
Name: Location, dtype: object

In [32]:
df['Location'][0:1]

0    33.9599 -118.3962
Name: Location, dtype: object

In [33]:
#type(pd.Series(computeNearestZip(34.0409,-118.2609)))

def ourWrapper(ourDF):
    lat = ourDF['latitude']
    long = ourDF['longitude']
    return computeNearestZip(lat,long)

In [34]:
# use apply function to apply the function that computes the nearest zip ( computeNearestZip(lat,long))
# and save results to a column called Zipcode in the same dataframe 

newdf['Zipcode'] = newdf.apply(func=ourWrapper, axis=1, raw=False)
newdf['Zipcode']

/Users/pcr_23/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

0       90045
1       90021
2       90015
3       90071
4       90015
5       90015
6       90071
7       90015
8       90071
9       90015
10      90014
11      90012
12      90014
13      90013
14      90017
15      90013
16      90014
17      90026
18      90015
19      90071
20      90012
21      90017
22      90014
23      90013
24      90012
25      90014
26      90071
27      90014
28      90013
29      90012
        ...
971     90013
972     90013
973     90014
974     90015
975     90015
976     90014
977     90071
978     90015
979     90071
980     90013
981     90013
982     90012
983     90014
984     90017
985     90015
986     90071
987     90015
988     90012
989     90015
990     90015
991     90014
992     90013
993     90017
994     90012
995     90015
996     90015
997     90071
998     90015
999     90015
1000    90013
Name: Zipcode, Length: 1001, dtype: object

In [35]:
# check the zipcode is a string data type
type(newdf['Zipcode'][0])

str

In [36]:
newdf.shape

(1001, 29)

In [37]:
# check the zipcode column created
newdf.dtypes

DR Number                   int64
Date Reported              object
Date Occurred              object
Time Occurred               int64
Area ID                     int64
Area Name                  object
Reporting District          int64
Crime Code                  int64
Crime Code Description     object
MO Codes                   object
Victim Age                  int64
Victim Sex                 object
Victim Descent             object
Premise Code              float64
Premise Description        object
Weapon Used Code          float64
Weapon Description         object
Status Code                object
Status Description         object
Crime Code 1              float64
Crime Code 2              float64
Crime Code 3              float64
Crime Code 4              float64
Address                    object
Cross Street               object
Location                   object
latitude                  float64
longitude                 float64
Zipcode                    object
dtype: object

In [38]:
# Export the resized dataset (newdf)
newdf.to_csv('Resources/CrimeData_2010-Present_resized.csv')

## Load data to SQL lite

In [39]:
# Python SQL toolkit and Object Relational Mapper
from sqlalchemy import create_engine

In [40]:
# database_path1 = "Resources/CrimeData_2010-Present_resized.sqlite"
database_path2 = "Resources/la_biz.sqlite"

In [42]:
database_path2

'Resources/la_biz.sqlite'

In [43]:
engine2 = create_engine(f"sqlite:///{database_path2}")

In [74]:
engine2.table_names()

['biz_profile', 'lacrimeData']

In [68]:
newdf.to_sql(name="lacrimeData", con=engine2, if_exists='append', index=False)

In [49]:
pd.read_sql_query('select * from crimeData', con=engine1).head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,latitude,longitude,Zipcode
0,11401303,9/13/10,9/12/10,45,14,Pacific,1485,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,740.0,NaN,NaN,None,SEPULVEDA BL,MANCHESTER AV,"(33.9599, -118.3962)",33.9599,-118.3962,90045
1,70309629,8/9/10,8/9/10,1515,13,Newton,1324,946,OTHER MISCELLANEOUS CRIME,344,...,946.0,NaN,NaN,None,1300 E 21ST ST,None,"(34.0224, -118.2524)",34.0224,-118.2524,90021
2,100100508,1/8/10,1/7/10,2005,1,Central,182,330,BURGLARY FROM VEHICLE,344,...,330.0,NaN,NaN,None,PICO BL,GRAND AV,"(34.0389, -118.2643)",34.0389,-118.2643,90015
3,100100511,1/9/10,1/6/10,2100,1,Central,132,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,341.0,998.0,NaN,None,200 S OLIVE ST,None,"(34.0538, -118.2488)",34.0538,-118.2488,90071
4,100100523,1/15/10,1/15/10,245,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,740.0,NaN,NaN,None,1100 S OLIVE ST,None,"(34.0409, -118.2609)",34.0409,-118.2609,90015

In [51]:
engine1.table_names()

['crimeData']

In [69]:
pd.read_sql_query('select * from lacrimeData', con=engine2).head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,latitude,longitude,Zipcode
0,11401303,9/13/10,9/12/10,45,14,Pacific,1485,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,740.0,NaN,NaN,None,SEPULVEDA BL,MANCHESTER AV,"(33.9599, -118.3962)",33.9599,-118.3962,90045
1,70309629,8/9/10,8/9/10,1515,13,Newton,1324,946,OTHER MISCELLANEOUS CRIME,344,...,946.0,NaN,NaN,None,1300 E 21ST ST,None,"(34.0224, -118.2524)",34.0224,-118.2524,90021
2,100100508,1/8/10,1/7/10,2005,1,Central,182,330,BURGLARY FROM VEHICLE,344,...,330.0,NaN,NaN,None,PICO BL,GRAND AV,"(34.0389, -118.2643)",34.0389,-118.2643,90015
3,100100511,1/9/10,1/6/10,2100,1,Central,132,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1402,...,341.0,998.0,NaN,None,200 S OLIVE ST,None,"(34.0538, -118.2488)",34.0538,-118.2488,90071
4,100100523,1/15/10,1/15/10,245,1,Central,182,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,740.0,NaN,NaN,None,1100 S OLIVE ST,None,"(34.0409, -118.2609)",34.0409,-118.2609,90015

In [70]:
pd.read_sql_query('select * from biz_profile', con=engine2).head()

,id,alias,name,categories,review_count,rating,lat,long,address,city,zip_code,country,state,phone
0,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,90017,US,CA,+12138021470
1,7O1ORGY36A-2aIENyaJWPg,howlin-rays-los-angeles-3,Howlin' Ray's,"Southern, Chicken Shop, American (Traditional)",5037,4.5,34.061486,-118.239555,"727 N Broadway Ste 128 Los Angeles, CA 90012",Los Angeles,90012,US,CA,+12139358399
2,KQBGm5G8IDkE8LeNY45mbA,wurstkÃ¼che-los-angeles-2,WurstkÃ¼che,"Hot Dogs, German, Gastropubs",8058,4.0,34.045605,-118.236061,"800 E 3rd St Los Angeles, CA 90013",Los Angeles,90013,US,CA,+12136874444
3,iSZpZgVnASwEmlq0DORY2A,daikokuya-little-tokyo-los-angeles,Daikokuya Little Tokyo,"Ramen, Noodles",8122,4.0,34.050081,-118.240180,"327 E 1st St Los Angeles, CA 90012",Los Angeles,90012,US,CA,+12136261680
4,DJek3FUewBzMc0gS-Gms9w,the-morrison-los-angeles,The Morrison,"Gastropubs, Burgers, Bars",4072,4.5,34.123840,-118.268680,"3179 Los Feliz Blvd Los Angeles, CA 90039",Los Angeles,90039,US,CA,+13236671839

In [71]:
engine2.table_names()

['biz_profile', 'lacrimeData']

In [52]:
pd.read_sql_query('SELECT zip_code FROM biz_profile', con=engine2).head()

  zip_code
0    90017
1    90012
2    90013
3    90012
4    90039

In [53]:
pd.read_sql_query('SELECT Zipcode FROM crimeData', con=engine1).head()

  Zipcode
0   90045
1   90021
2   90015
3   90071
4   90015

In [73]:
# table joined on Zipcode with the 2 original tables in the database

pd.read_sql_query('SELECT * FROM biz_profile INNER JOIN lacrimeData ON biz_profile.zip_code = lacrimeData.Zipcode', con=engine2)

,id,alias,name,categories,review_count,rating,lat,long,address,city,...,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,latitude,longitude,Zipcode
0,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,341.0,998.0,None,None,7TH,FIGUEROA,"(34.0499, -118.2614)",34.0499,-118.2614,90017
1,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,946.0,NaN,None,None,900 GEORGIA ST,None,"(34.0475, -118.2657)",34.0475,-118.2657,90017
2,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,745.0,NaN,None,None,9TH ST,FLOWER ST,"(34.0458, -118.2614)",34.0458,-118.2614,90017
3,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,354.0,NaN,None,None,800 S FIGUEROA ST,None,"(34.0479, -118.2612)",34.0479,-118.2612,90017
4,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,341.0,NaN,None,None,800 S FIGUEROA ST,None,"(34.0479, -118.2612)",34.0479,-118.2612,90017
5,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,8TH,FLOWER,"(34.0473, -118.2601)",34.0473,-118.2601,90017
6,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,624.0,NaN,None,None,WILSHIRE,FIGUEROA,"(34.0509, -118.2605)",34.0509,-118.2605,90017
7,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,8TH ST,FRANCISCO ST,"(34.0487, -118.2627)",34.0487,-118.2627,90017
8,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,9TH,FRANCISCO,"(34.0469, -118.2644)",34.0469,-118.2644,90017
9,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,1000 W OLYMPIC BL,None,"(34.0459, -118.2669)",34.0459,-118.2669,90017
10,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,GEORGIA,JAMES M WOOD,"(34.0459, -118.2668)",34.0459,-118.2668,90017
11,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,740.0,998.0,None,None,1000 W OLYMPIC BL,None,"(34.0459, -118.2669)",34.0459,-118.2669,90017
12,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,740.0,NaN,None,None,800 S FLOWER ST,None,"(34.0473, -118.2601)",34.0473,-118.2601,90017
13,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,331.0,NaN,None,None,9TH,FIGUEROA,"(34.0462, -118.2628)",34.0462,-118.2628,90017
14,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,745.0,NaN,None,None,900 W 8TH ST,None,"(34.0479, -118.2612)",34.0479,-118.2612,90017
15,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,956.0,NaN,None,None,800 JAMES M WOOD BL,None,"(34.0462, -118.2628)",34.0462,-118.2628,90017
16,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,740.0,NaN,None,None,9TH ST,GEORGIA ST,"(34.0475, -118.2657)",34.0475,-118.2657,90017
17,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,11TH ST,ALBANY AV,"(34.0464, -118.2721)",34.0464,-118.2721,90017
18,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,420.0,NaN,None,None,9TH,FIGUEROA,"(34.0462, -118.2628)",34.0462,-118.2628,90017
19,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,341.0,NaN,None,None,7TH ST,FRANCISCO ST,"(34.0499, -118.2614)",34.0499,-118.2614,90017
20,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,8TH ST,FIGUEROA ST,"(34.0487, -118.2627)",34.0487,-118.2627,90017
21,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,341.0,NaN,None,None,800 S FIGUEROA ST,None,"(34.0479, -118.2612)",34.0479,-118.2612,90017
22,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,JAMES M WOOD,FRANCISCO,"(34.0469, -118.2644)",34.0469,-118.2644,90017
23,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,740.0,NaN,None,None,JAMES M WOOD,FIGUEROA ST,"(34.0468, -118.2641)",34.0468,-118.2641,90017
24,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,230.0,NaN,None,None,GEORGIA ST,9TH ST,"(34.0459, -118.2668)",34.0459,-118.2668,90017
25,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,230.0,NaN,None,None,GEORGIA,OLYMPIC BL,"(34.0459, -118.2657)",34.0459,-118.2657,90017
26,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,745.0,NaN,None,None,8TH ST,FRANCISCO,"(34.0487, -118.2627)",34.0487,-118.2627,90017
27,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,745.0,NaN,None,None,WILSHIRE BL,FIGUEROA ST,"(34.0509, -118.2605)",34.0509,-118.2605,90017
28,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,510.0,NaN,None,None,JAMES M WOOD,GEORGIA,"(34.0475, -118.2657)",34.0475,-118.2657,90017
29,TkFEKhsCixPWlShULKvMdQ,bottega-louie-los-angeles,Bottega Louie,"Italian, Bakeries, Breakfast & Brunch",16243,4.0,34.046930,-118.256601,"700 S Grand Ave Los Angeles, CA 90017",Los Angeles,...,740.0,NaN,None,None,8TH,FLOWER,"(34.0473, -118.2601)",34.0473,-118.2601,90017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44950,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,624.0,NaN,None,None,500 E 6TH ST,None,"(34.0423, -118.2452)",34.0423,-118.2452,90013
44951,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,930.0,NaN,None,None,200 N MAIN ST,None,"(34.0532, -118.2425)",34.0532,-118.2425,90013
44952,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,341.0,NaN,None,None,300 E 2ND ST,None,"(34.0493, -118.2418)",34.0493,-118.2418,90013
44953,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,740.0,NaN,None,None,700 E 6TH ST,None,"(34.0412, -118.2436)",34.0412,-118.2436,90013
44954,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,510.0,NaN,None,None,1200 E 6TH ST,None,"(34.0382, -118.2384)",34.0382,-118.2384,90013
44955,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,623.0,998.0,None,None,5TH,SAN JULIAN,"(34.0446, -118.245)",34.0446,-118.2450,90013
44956,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,624.0,NaN,None,None,600 S SAN PEDRO ST,None,"(34.0423, -118.2452)",34.0423,-118.2452,90013
44957,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,230.0,NaN,None,None,600 S SAN PEDRO ST,None,"(34.0423, -118.2452)",34.0423,-118.2452,90013
44958,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,745.0,NaN,None,None,300 S SPRING ST,None,"(34.0503, -118.247)",34.0503,-118.2470,90013
44959,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,860.0,NaN,None,None,WALL ST,6TH ST,"(34.0435, -118.2471)",34.0435,-118.2471,90013
44960,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,341.0,NaN,None,None,5TH,SAN JULIAN,"(34.0446, -118.245)",34.0446,-118.2450,90013
44961,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,930.0,946.0,None,None,200 S MAIN ST,None,"(34.051, -118.2445)",34.0510,-118.2445,90013
44962,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,624.0,NaN,None,None,600 WALL ST,None,"(34.0435, -118.2471)",34.0435,-118.2471,90013
44963,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,946.0,NaN,None,None,500 S LOS ANGELES ST,None,"(34.0461, -118.2476)",34.0461,-118.2476,90013
44964,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,626.0,745.0,None,None,6TH,TOWNE,"(34.0408, -118.2428)",34.0408,-118.2428,90013
44965,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,510.0,NaN,None,None,100 S ASTRONAUT AV,None,"(34.0498, -118.24)",34.0498,-118.2400,90013
44966,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,930.0,NaN,None,None,500 S SAN PEDRO ST,None,"(34.0442, -118.2439)",34.0442,-118.2439,90013
44967,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,510.0,NaN,None,None,5TH,SAN JULIAN,"(34.0446, -118.245)",34.0446,-118.2450,90013
44968,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,624.0,NaN,None,None,400 E 5TH ST,None,"(34.0446, -118.245)",34.0446,-118.2450,90013
44969,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,341.0,NaN,None,None,200 S SPRING ST,None,"(34.0517, -118.2456)",34.0517,-118.2456,90013
44970,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,341.0,NaN,None,None,400 E 4TH ST,None,"(34.0458, -118.243)",34.0458,-118.2430,90013
44971,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,420.0,NaN,None,None,600 WALL ST,None,"(34.0435, -118.2471)",34.0435,-118.2471,90013
44972,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,510.0,NaN,None,None,6TH,CROCKER,"(34.0412, -118.2436)",34.0412,-118.2436,90013
44973,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,930.0,NaN,None,None,500 S SAN PEDRO ST,None,"(34.0442, -118.2439)",34.0442,-118.2439,90013
44974,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,930.0,NaN,None,None,500 S SAN PEDRO ST,None,"(34.0442, -118.2439)",34.0442,-118.2439,90013
44975,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,755.0,995.0,None,None,100 N LOS ANGELES ST,None,"(34.0515, -118.2424)",34.0515,-118.2424,90013
44976,gd6PYDx-leOM97a3MWoO1g,maccheroni-republic-los-angeles,Maccheroni Republic,"Italian, Wine Bars",2587,4.0,34.050039,-118.248552,"332 S Broadway Los Angeles, CA 90013",Los Angeles,...,928.0,NaN,None,None,500 S SAN PEDRO ST,None,"(34.0442, -118.2439)",34.0442,-118.2439,90013
44977,qpcH_Fub586U2kw_pQJS3w,guisados-los-angeles,Guisados,Mexican,2340,4.5,34.048120,-118.211470,"2100 East Cesar E Chavez Ave Los Angeles, CA 9...",Los Angeles,...,745.0,NaN,None,None,200 E BOYLE ST,None,"(34.0486, -118.2192)",34.0486,-118.2192,90033
44978,BDRVlHnK4l0T0ANb7M-Eqg,guisados-los-angeles-3,Guisados,Mexican,1937,4.5,34.070240,-118.250448,"1261 W Sunset Blvd Los Angeles, CA 90026",Los Angeles,...,946.0,998.0,None,None,WAVERLY,SUNSET BL,"(34.0917, -118.2741)",34.0917,-118.2741,90026
44979,ohosmz6FXVAeoW5nUkYwng,pine-and-crane-los-angeles,Pine & Crane,"Taiwanese, Chinese, Bubble Tea",2011,4.5,34.090596,-118.277172,"1521 Griffith Park Blvd Los Angeles, CA 90026",Los Angeles,...,946.0,998.0,None,None,WAVERLY,SUNSET BL,"(34.0917, -118.2741)",34.0917,-118.2741,90026